# @name login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "identity": "user64@example.com",
  "password": "examplepassword"
}

### Obtener información del usuario autenticado
### Capturar el token de acceso
@accessToken = {{login.response.body.data.accessToken}}
@refreshToken = {{login.response.body.data.refreshToken}}

### Obtener todos los Condominiums con paginación

### Obtener todos los Condominiums con paginación
# @name GetCondominiums
GET {{host}}{{endpointCon}}?page=1&pageSize=10&preload=true
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Crear un nuevo Building
@idCondominium = {{GetCondominiums.response.body.data.items[0].id}}
@idBuilding = {{GetCondominiums.response.body.data.items[0].buildings[0].id}}

### Obtener un Building por ID
GET {{host}}/api/buildings/{{idBuilding}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}



### Crear un nuevo Resident
POST {{host}}/api/residents
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "user_id": 1,
  "apartment_id": 1,
  "first_name": "John",
  "last_name": "Connor",
  "phone": "1234567890",
  "email": "john.doe@example.com",
  "estatus": "Active"
}

### Obtener un Resident por ID
GET {{host}}/api/residents/4
Authorization: Bearer {{accessToken}}

### Obtener todos los Residents con paginación
GET {{host}}/api/residents?page=1&pageSize=10
Authorization: Bearer {{accessToken}}

### Actualizar un Resident por ID
PATCH {{host}}/api/residents/4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "apartment_id": 1,
  "first_name": "Jane",
  "last_name": "Doe",
  "phone": "0987654321",
  "email": "jane.doe@example.com",
  "estatus": "Inactive",
  "user_id": 1
}

### Eliminar un Resident por ID
DELETE {{host}}/api/residents/1
Authorization: Bearer {{accessToken}}