basePath: /api
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for managing condominiums, buildings, apartments, and residents.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Condominium Management API
  version: "1.0"
paths:
  /condominiums:
    post:
      responses: {}
swagger: "2.0"
